-- SAHODARA PHARMACY - CONSOLIDATED UPGRADE SETUP
-- Run once in Supabase SQL Editor.

-- Product fields
alter table public.products add column if not exists brand text default '';
alter table public.products add column if not exists formula text default '';
alter table public.products add column if not exists stock_quantity integer not null default 6;

-- Advertisement slides (customer app: max 3 active/displayed by admin UI)
create table if not exists public.ad_slides (
  id text primary key,
  image text not null,
  title text default '',
  subtitle text default '',
  link text default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
alter table public.ad_slides enable row level security;

-- Customer account data
create table if not exists public.customer_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text default '', phone text default '', email text default '',
  created_at timestamptz not null default now()
);
create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text default 'Home', address text not null, phone text default '',
  is_default boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.customer_wishlist (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null, created_at timestamptz not null default now(),
  primary key(user_id, product_id)
);
create table if not exists public.customer_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null, message text not null, read boolean not null default false,
  created_at timestamptz not null default now()
);
create table if not exists public.customer_offers (
  id text primary key,
  title text not null, description text default '',
  min_order numeric(12,2) not null default 0,
  discount_percent numeric(5,2) not null default 0,
  gift_product_id text, gift_product_name text, gift_value numeric(12,2) default 0,
  active boolean not null default true, starts_at timestamptz, ends_at timestamptz,
  created_at timestamptz not null default now()
);

-- Customer order ownership / prescription reference
alter table public.customer_orders add column if not exists order_user_id uuid;
alter table public.customer_orders add column if not exists prescription_path text;

-- Enable RLS
alter table public.customer_profiles enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.customer_wishlist enable row level security;
alter table public.customer_notifications enable row level security;
alter table public.customer_offers enable row level security;

-- Policies, created safely only when absent
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_profiles' AND policyname='customers manage own profile') THEN
    CREATE POLICY "customers manage own profile" ON public.customer_profiles FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_addresses' AND policyname='customers manage own addresses') THEN
    CREATE POLICY "customers manage own addresses" ON public.customer_addresses FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_wishlist' AND policyname='customers manage own wishlist') THEN
    CREATE POLICY "customers manage own wishlist" ON public.customer_wishlist FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_notifications' AND policyname='customers read own notifications') THEN
    CREATE POLICY "customers read own notifications" ON public.customer_notifications FOR SELECT TO authenticated USING (auth.uid()=user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_notifications' AND policyname='customers mark own notifications') THEN
    CREATE POLICY "customers mark own notifications" ON public.customer_notifications FOR UPDATE TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_offers' AND policyname='public read active offers') THEN
    CREATE POLICY "public read active offers" ON public.customer_offers FOR SELECT TO anon, authenticated USING (active=true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_offers' AND policyname='receiver manage offers') THEN
    CREATE POLICY "receiver manage offers" ON public.customer_offers FOR ALL TO anon USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_notifications' AND policyname='receiver insert notifications') THEN
    CREATE POLICY "receiver insert notifications" ON public.customer_notifications FOR INSERT TO anon WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='customer_notifications' AND policyname='receiver read notifications') THEN
    CREATE POLICY "receiver read notifications" ON public.customer_notifications FOR SELECT TO anon USING (true);
  END IF;
END $$;

-- Existing prototype access pattern. Harden later using a server-side admin/auth role.
grant usage on schema public to anon, authenticated;
grant select, insert, update on public.products to anon, authenticated;
grant select, insert, update on public.customer_orders to anon, authenticated;
grant select, insert, update, delete on public.ad_slides to anon, authenticated;
grant select, insert, update, delete on public.customer_offers to anon;
grant select on public.customer_offers to authenticated;
grant select, insert, update, delete on public.customer_profiles, public.customer_addresses, public.customer_wishlist to authenticated;
grant select, insert, update on public.customer_notifications to authenticated;
grant insert, select on public.customer_notifications to anon;

-- IMPORTANT AUTH SETUP
-- 1) Supabase Dashboard -> Authentication -> Providers: keep Email enabled.
-- 2) Enable Phone authentication and configure an SMS provider before phone/password signup/login.
-- 3) Authentication -> URL Configuration: set your Netlify Site URL and add its redirect URL.
-- 4) Configure SMTP for production password-reset emails.
-- 5) Create a PRIVATE Storage bucket named "prescriptions" before enabling prescription uploads.

