-- Sahodara Pharmacy notification system
-- Run once in Supabase SQL Editor.
create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_notification_state (
  user_id uuid primary key,
  next_index integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.abandoned_product_reminders (
  user_id uuid primary key,
  product_id text not null,
  product_name text not null,
  price numeric(12,2) not null default 0,
  mrp numeric(12,2) not null default 0,
  scheduled_at timestamptz not null,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;
alter table public.product_notification_state enable row level security;
alter table public.abandoned_product_reminders enable row level security;

-- Browser clients should not read the push tables directly. Netlify Functions use the service-role key.
-- Optional cleanup function for old subscriptions.

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
create index if not exists abandoned_product_due_idx on public.abandoned_product_reminders(scheduled_at) where sent_at is null;

-- Make sure the existing in-app notification table can accept product/basket messages.
-- Existing customer_notifications table is reused by the functions.
